---
name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  node_version: "12.x"

jobs:
  unittests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - uses: c-hive/gha-npm-cache@v1

      - name: installing dependencies
        run: npm ci

      - name: run tests
        run: npm run all

  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - uses: c-hive/gha-npm-cache@v1

      - name: installing dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Package
        run: npm run package

      - name: fail if build wasn't commited
        run: |
          if [ ! -z "$(git status --porcelain)" ]; then
            # If we get a fail here then this workflow needs attention...
            >&2 echo "Failed: Repo should be clean before testing!"
            exit 1
          fi

      # - name: Commit and push distified version
      #   uses: EndBug/add-and-commit@v5
      #   with:
      #     message: 'Update distified version'
      #     add: "dist"
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}

  actiontest:
    name: test action
    needs: test_build

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
