---
name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  node_version: "12.x"

jobs:
  unittests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - uses: c-hive/gha-npm-cache@v1

      - run: npm install

      - run: npm run all

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}

      - uses: c-hive/gha-npm-cache@v1

      - name: Install JS dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Package
        run: npm run package

      - name: Commit and push distified version
        # run: |
        #   git config --global user.name 'autoblack'
        #   git config --global user.email 'cclauss@users.noreply.github.com'
        #   git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        #   git checkout $GITHUB_HEAD_REF
        #   git commit -am "fixup: build and package code"
        #   git push
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: 'Update distified version'
          file_pattern: 'dist/**/*.js'

  actiontest:
    name: test action
    needs: build

    strategy:
      max-parallel: 1
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
